### ISSUE TITLE
User search broke

### ISSUE THREAD

**Issue by swiftSwathSee** [nortxort/pinylib-rtc#4]
In pinylib.py anything that does `_user = self.users.search(uid)` is returning None and causing a fatal error. Started happening like 2 days ago.

**Comment by swiftSwathSee** [comment]
Actually, it's just in `on_unpublish`. Putting the last 2 lines into a `if _user != None:` conditional is a valid workaround.

**Comment by Technetium1** [comment]
https://github.com/nortxort/pinylib-rtc/commit/db16987147ebc987b7d5c790145f5816d59ea063#diff-78ebb9159d0f2e62a68dd98ab604723eR498 user is cleared on exit, so you can't mark them as not broadcasting after they are gone.

**Comment by nortxort** [comment]
Thanks @swiftSwathSee and @Technetium1 i will add it in a moment.
